#server:
#  servlet:
#    context-path: /courses_api
spring:
  application:
    name: CoursesAPI
  datasource:
    url: jdbc:mysql://localhost:3306/courses_api?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    # Flyway config:
    flyway:
      locations: classpath:db/migration
    # Spring Security:
  security:
    user:
      name: root
      password: 1234
  jpa:
    hibernate:
      ddl-auto: update
