#server:
#  servlet:
#    context-path: /courses_api
spring:
  application:
    name: CoursesAPI
  datasource:
    url: jdbc:h2:mem:courses_api
    username: root
    password: 1234
    driverClassName: org.h2.Driver
    h2:
      console:
        enabled: true
#        path: /h2
    # Flyway config:
    flyway:
      locations: classpath:db/migration
    # Spring Security:
#  security:
#    user:
#      name: root
#      password: 1234
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

    hibernate:
      ddl-auto: update
